name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Run Bun tests
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun test